import React from "react";
import Head from "next/head";

import Header from "@/layout/components/header";

import { MainLayoutProps } from "./types";
import * as Styled from "./main.styled";

const MainLayout: React.FunctionComponent<MainLayoutProps> = ({
  children,
  pageTitle,
}) => {
  return (
    <Styled.MainLayout>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>{children}</div>
    </Styled.MainLayout>
  );
};

export default MainLayout;
